// // Menus x
// menus: [
//   {
//     id: 1,
//     name: 'Giới thiệu',
//     url: '/company',
//     dropdown: true,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 2,
//     name: 'Tin tức',
//     url: '/news',
//     dropdown: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 3,
//     name: 'Dịch vụ huấn luyện',
//     url: '/training-services',
//     dropdown: true,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 4,
//     name: 'Thiết bị huấn luyện và các tiện ích',
//     url: '/devices-utilities',
//     dropdown: true,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 5,
//     name: 'Tuyển sinh',
//     url: '/admissions',
//     dropdown: true,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 6,
//     name: 'Dành cho học viên',
//     url: '/information-for-trainees',
//     dropdown: true,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 7,
//     name: 'Sơ đồ website',
//     url: '/site-map',
//     dropdown: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 8,
//     name: 'Introduction',
//     url: '/company',
//     dropdown: true,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 9,
//     name: 'News',
//     url: '/news',
//     dropdown: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 10,
//     name: 'Training Services',
//     url: '/training-services',
//     dropdown: true,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 11,
//     name: 'Training Devices and Utilities',
//     url: '/devices-utilities',
//     dropdown: true,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 12,
//     name: 'Admissions',
//     url: '/admissions',
//     dropdown: true,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 13,
//     name: 'Information for Trainees',
//     url: '/information-for-trainees',
//     dropdown: true,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 14,
//     name: 'Site Map',
//     url: '/site-map',
//     dropdown: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   }
// ]

// // subMenu x
// subMenus: [
//   {
//     id: 1,
//     name: 'Lịch sử hình thành',
//     url: '/company/history-foundation',
//     menuId: 1,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 2,
//     name: 'Hệ thống chất lượng',
//     url: '/company/quality-system',
//     menuId: 1,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 3,
//     name: 'Sơ đồ vị trí',
//     url: '/company/location-map',
//     menuId: 1,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 4,
//     name: 'Hỏi đáp',
//     url: '/company/Q&A',
//     menuId: 1,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 5,
//     name: 'Khách hàng',
//     url: '/company/customer',
//     menuId: 1,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 6,
//     name: 'Liên hệ',
//     url: '/company/contact',
//     menuId: 1,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 7,
//     name: 'Huấn luyện phi công',
//     url: '/training-services/pilot-training',
//     menuId: 3,
//     subMenus: true,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 8,
//     name: 'Huấn luyện Tiếp viên hàng không',
//     url: '/training-services/flight-attendant-training',
//     menuId: 3,
//     subMenus: true,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 9,
//     name: 'Huấn luyện nhân viên khai thác/điều phái bay',
//     url: '/training-services/flight-operations-dispatch-personnel-training',
//     menuId: 3,
//     subMenus: true,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 10,
//     name: 'Huấn luyện kỹ năng mềm',
//     url: '/training-services/soft-skills-training',
//     menuId: 3,
//     subMenus: true,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 11,
//     name: 'Huấn luyện tiếng Anh hàng không',
//     url: '/training-services/aviation-english-training',
//     menuId: 3,
//     subMenus: true,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 12,
//     name: 'Hướng nghiệp hàng không',
//     url: '/training-services/aviation-career-guidance',
//     menuId: 3,
//     subMenus: true,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 13,
//     name: 'Thiết bị huấn luyện chuyên ngành',
//     url: '/devices-utilities/training-devices',
//     menuId: 4,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 14,
//     name: 'Phòng học',
//     url: '/devices-utilities/classroom',
//     menuId: 4,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 15,
//     name: 'Học viên phi công cơ bản',
//     url: '/admissions/student-pilot',
//     menuId: 5,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 16,
//     name: 'Thư viện tài liệu',
//     url: '/information-for-trainees/library',
//     menuId: 6,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 17,
//     name: 'Lịch huấn luyện',
//     url: '/information-for-trainees/training-schedule',
//     menuId: 6,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 18,
//     name: 'Sơ đồ phòng học',
//     url: '/information-for-trainees/classroom-layout',
//     menuId: 6,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 19,
//     name: 'Phiếu đánh giá khóa học',
//     url: '/information-for-trainees/evaluation-form',
//     menuId: 6,
//     subMenus: false,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 20,
//     name: 'History and Foundation',
//     url: '/company/history-foundation',
//     menuId: 8,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 21,
//     name: 'Quality System',
//     url: '/company/quality-system',
//     menuId: 8,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 22,
//     name: 'Location Map',
//     url: '/company/location-map',
//     menuId: 8,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 23,
//     name: 'Q&A',
//     url: '/company/Q&A',
//     menuId: 8,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 24,
//     name: 'Customer',
//     url: '/company/customer',
//     menuId: 8,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 25,
//     name: 'Contact',
//     url: '/company/contact',
//     menuId: 8,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 26,
//     name: 'Pilot Training',
//     url: '/training-services/pilot-training',
//     menuId: 10,
//     subMenus: true,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 27,
//     name: 'Flight Attendant Training',
//     url: '/training-services/flight-attendant-training',
//     menuId: 10,
//     subMenus: true,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 28,
//     name: 'Flight Operations and Dispatch Personnel Training',
//     url: '/training-services/flight-operations-dispatch-personnel-training',
//     menuId: 10,
//     subMenus: true,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 29,
//     name: 'Soft Skills Training',
//     url: '/training-services/soft-skills-training',
//     menuId: 10,
//     subMenus: true,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 30,
//     name: 'Aviation English Training',
//     url: '/training-services/aviation-english-training',
//     menuId: 10,
//     subMenus: true,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 31,
//     name: 'Aviation Career Guidance',
//     url: '/training-services/aviation-career-guidance',
//     menuId: 10,
//     subMenus: true,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 32,
//     name: 'Specialized Training Devices',
//     url: '/devices-utilities/training-devices',
//     menuId: 11,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 33,
//     name: 'Classroom',
//     url: '/devices-utilities/classroom',
//     menuId: 11,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 34,
//     name: 'Basic Student Pilot',
//     url: '/admissions/student-pilot',
//     menuId: 12,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 35,
//     name: 'Library',
//     url: '/information-for-trainees/library',
//     menuId: 13,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 36,
//     name: 'Training Schedule',
//     url: '/information-for-trainees/training-schedule',
//     menuId: 13,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 37,
//     name: 'Classroom Layout',
//     url: '/information-for-trainees/classroom-layout',
//     menuId: 13,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 38,
//     name: 'Course Evaluation Form',
//     url: '/information-for-trainees/evaluation-form',
//     menuId: 13,
//     subMenus: false,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   }
// ]

// // TrainingServices
// trainingServices: [
//   {
//     id: 1,
//     name: 'Huấn luyện chuyển loại',
//     url: 'ATR72-type-rating-training-pl',
//     routeName: 'PilotTrainingDetail',
//     img: 'article.jpg',
//     description: 'ATR72 Type Rating Training',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 7,
//     subMenus: true,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 2,
//     name: 'Huấn luyện an toàn khai thác',
//     url: 'safety-operations-training',
//     img: 'article.jpg',
//     routeName: 'PilotTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 7,
//     subMenus: false,
//     description: 'Huấn luyện an toàn khai thác description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 3,
//     name: 'Huấn luyện làm quen máy bay phản lực',
//     url: 'jet-aircraft-familiarization-training',
//     img: 'article.jpg',
//     routeName: 'PilotTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 7,
//     subMenus: false,
//     description: 'Huấn luyện làm quen máy bay phản lực description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 4,
//     name: 'Huấn luyện Tổ lái nhiều thành viên',
//     url: 'multi-crew-pilot-training',
//     img: 'article.jpg',
//     routeName: 'PilotTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 7,
//     subMenus: false,
//     description: 'Huấn luyện Tổ lái nhiều thành viên description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 5,
//     name: 'Kiểm tra đánh giá trình độ thông thạo tiếng Anh',
//     url: 'english-proficiency-assessment',
//     img: 'article.jpg',
//     routeName: 'PilotTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 7,
//     subMenus: false,
//     description: 'Kiểm tra đánh giá trình độ thông thạo tiếng Anh description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 6,
//     name: 'Huấn luyện chuyển nhà khai thác',
//     url: 'operator-transition-training',
//     img: 'article.jpg',
//     routeName: 'PilotTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 7,
//     subMenus: false,
//     description: 'Huấn luyện chuyển nhà khai thác description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 7,
//     name: 'Huấn luyện tiếp viên cơ bản',
//     url: 'basic-cabin-crew-training',
//     img: 'article.jpg',
//     routeName: 'FATrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 8,
//     subMenus: false,
//     description: 'Huấn luyện tiếp viên cơ bản description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 8,
//     name: 'Huấn luyện chuyển loại An toàn bay',
//     url: 'flight-safety-type-rating-training',
//     img: 'article.jpg',
//     routeName: 'FATrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 8,
//     subMenus: true,
//     description: 'Huấn luyện chuyển loại An toàn bay description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 9,
//     name: 'Huấn luyện tiếp viên trưởng',
//     url: 'senior-cabin-crew-training',
//     img: 'article.jpg',
//     routeName: 'FATrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 8,
//     subMenus: false,
//     description: 'Huấn luyện tiếp viên trưởng description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 10,
//     name: 'Huấn luyện định kỳ an toàn khai thác phối hợp',
//     url: 'periodic-coordinated-safety-operations-training',
//     img: 'article.jpg',
//     routeName: 'FATrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 8,
//     subMenus: false,
//     description: 'Huấn luyện định kỳ an toàn khai thác phối hợp description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 11,
//     name: 'Huấn luyện phục hồi',
//     url: 'recovery-training-fa',
//     img: 'article.jpg',
//     routeName: 'FATrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 8,
//     subMenus: false,
//     description: 'Huấn luyện phục hồi description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 12,
//     name: 'Huấn luyện cơ bản',
//     url: 'basic-training',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'FODPTrainingDetail',
//     subMenuId: 9,
//     subMenus: false,
//     description: 'Huấn luyện cơ bản description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 13,
//     name: 'Huấn luyện định kỳ',
//     url: 'periodic-training',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'FODPTrainingDetail',
//     subMenuId: 9,
//     subMenus: false,
//     description: 'Huấn luyện định kỳ description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 14,
//     name: 'Huấn luyện phục hồi',
//     url: 'recovery-training-od',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'FODPTrainingDetail',
//     subMenuId: 9,
//     subMenus: false,
//     description: 'Huấn luyện phục hồi description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 15,
//     name: 'Huấn luyện quan hệ khách hàng',
//     url: 'customer-service-training',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'SSTrainingDetail',
//     subMenuId: 10,
//     subMenus: false,
//     description: 'Huấn luyện quan hệ khách hàng description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 16,
//     name: 'Huấn luyện trang điểm - trang phục',
//     url: 'makeup-and-uniform-training',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'SSTrainingDetail',
//     subMenuId: 10,
//     subMenus: false,
//     description: 'Huấn luyện trang điểm - trang phục description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 17,
//     name: 'Huấn luyện kỹ năng làm việc nhóm',
//     url: 'teamwork-skills-training',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'SSTrainingDetail',
//     subMenuId: 10,
//     subMenus: false,
//     description: 'Huấn luyện kỹ năng làm việc nhóm description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 18,
//     name: 'Kỹ năng quản lý và lãnh đạo',
//     url: 'management-and-leadership-skills',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'SSTrainingDetail',
//     subMenuId: 10,
//     subMenus: false,
//     description: 'Kỹ năng quản lý và lãnh đạo description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 19,
//     name: 'Kỹ năng phát thanh tiếng Anh trên chuyến bay',
//     url: 'in-flight-english-announcement-skills',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'AETrainingDetail',
//     subMenuId: 11,
//     subMenus: false,
//     description: 'Kỹ năng phát thanh tiếng Anh trên chuyến bay description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 20,
//     name: 'Tiếng Anh hàng không cơ bản',
//     url: 'basic-aviation-english',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'AETrainingDetail',
//     subMenuId: 11,
//     subMenus: false,
//     description: 'Tiếng Anh hàng không cơ bản description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 21,
//     name: 'Tiếng Anh hàng không nâng cao',
//     url: 'advanced-aviation-english',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'AETrainingDetail',
//     subMenuId: 11,
//     subMenus: false,
//     description: 'Tiếng Anh hàng không nâng cao description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 22,
//     name: 'Bay cùng trung tâm Huấn luyện bay',
//     url: 'fly-with-the-flight-training-center',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'ACGuidanceDetail',
//     subMenuId: 12,
//     subMenus: false,
//     description: 'Bay cùng trung tâm Huấn luyện bay description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 23,
//     name: 'Tham quan mô hình đào tạo của Trung tâm Huấn luyện bay',
//     url: 'visit-the-training-model-of-the-flight-training-center',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'ACGuidanceDetail',
//     subMenuId: 12,
//     subMenus: false,
//     description: 'Tham quan mô hình đào tạo của Trung tâm Huấn luyện bay description !',
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 24,
//     name: 'Type Rating Training',
//     url: 'ATR72-type-rating-training-pl',
//     img: 'article.jpg',
//     description: 'ATR72 Type Rating Training',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 26,
//     subMenus: true,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 25,
//     name: 'Safety Operations Training',
//     url: 'safety-operations-training',
//     img: 'article.jpg',
//     routeName: 'PilotTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 26,
//     subMenus: false,
//     description: 'Safety Operations Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 26,
//     name: 'Jet Aircraft Familiarization Training',
//     url: 'jet-aircraft-familiarization-training',
//     img: 'article.jpg',
//     routeName: 'PilotTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 26,
//     subMenus: false,
//     description: 'Jet Aircraft Familiarization Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 27,
//     name: 'Multi-Crew Pilot Training',
//     url: 'multi-crew-pilot-training',
//     img: 'article.jpg',
//     routeName: 'PilotTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 26,
//     subMenus: false,
//     description: 'Multi-Crew Pilot Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 28,
//     name: 'English Proficiency Assessment',
//     url: 'english-proficiency-assessment',
//     img: 'article.jpg',
//     routeName: 'PilotTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 26,
//     subMenus: false,
//     description: 'English Proficiency Assessment description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 29,
//     name: 'Operator Transition Training',
//     url: 'operator-transition-training',
//     img: 'article.jpg',
//     routeName: 'PilotTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 26,
//     subMenus: false,
//     description: 'Operator Transition Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 30,
//     name: 'Basic Cabin Crew Training',
//     url: 'basic-cabin-crew-training',
//     img: 'article.jpg',
//     routeName: 'FATrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 27,
//     subMenus: false,
//     description: 'Basic Cabin Crew Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 31,
//     name: 'Flight Safety Type Rating Training',
//     url: 'flight-safety-type-rating-training',
//     img: 'article.jpg',
//     routeName: 'FATrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 27,
//     subMenus: true,
//     description: 'Flight Safety Type Rating Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 32,
//     name: 'Senior Cabin Crew Training',
//     url: 'senior-cabin-crew-training',
//     img: 'article.jpg',
//     routeName: 'FATrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 27,
//     subMenus: false,
//     description: 'Senior Cabin Crew Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 33,
//     name: 'Periodic Coordinated Safety Operations Training',
//     url: 'periodic-coordinated-safety-operations-training',
//     img: 'article.jpg',
//     routeName: 'FATrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 27,
//     subMenus: false,
//     description: 'Periodic Coordinated Safety Operations Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 34,
//     name: 'Recovery Training',
//     url: 'recovery-training-fa',
//     img: 'article.jpg',
//     routeName: 'FATrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 27,
//     subMenus: false,
//     description: 'Recovery Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 35,
//     name: 'Basic Training',
//     url: 'basic-training',
//     img: 'article.jpg',
//     routeName: 'FODPTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 28,
//     subMenus: false,
//     description: 'Basic Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 36,
//     name: 'Periodic Training',
//     url: 'periodic-training',
//     img: 'article.jpg',
//     routeName: 'FODPTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 28,
//     subMenus: false,
//     description: 'Periodic Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 37,
//     name: 'Recovery Training',
//     url: 'recovery-training-od',
//     img: 'article.jpg',
//     routeName: 'FODPTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 28,
//     subMenus: false,
//     description: 'Recovery Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 38,
//     name: 'Customer Service Training',
//     url: 'customer-service-training',
//     img: 'article.jpg',
//     routeName: 'SSTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 29,
//     subMenus: false,
//     description: 'Customer Service Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 39,
//     name: 'Makeup and Uniform Training',
//     url: 'makeup-and-uniform-training',
//     img: 'article.jpg',
//     routeName: 'SSTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 29,
//     subMenus: false,
//     description: 'Makeup and Uniform Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 40,
//     name: 'Teamwork Skills Training',
//     url: 'teamwork-skills-training',
//     img: 'article.jpg',
//     routeName: 'SSTrainingDetail',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     subMenuId: 29,
//     subMenus: false,
//     description: 'Teamwork Skills Training description!',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 41,
//     name: 'Management and Leadership Skills',
//     url: 'management-and-leadership-skills',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'SSTrainingDetail',
//     subMenuId: 29,
//     subMenus: false,
//     description: 'Management and Leadership Skills description !',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 42,
//     name: 'In-Flight English Announcement Skills',
//     url: 'in-flight-english-announcement-skills',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'AETrainingDetail',
//     subMenuId: 30,
//     subMenus: false,
//     description: 'In-Flight English Announcement Skills description !',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 43,
//     name: 'Basic Aviation English',
//     url: 'basic-aviation-english',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'AETrainingDetail',
//     subMenuId: 30,
//     subMenus: false,
//     description: 'Basic Aviation English description !',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 44,
//     name: 'Advanced Aviation English',
//     url: 'advanced-aviation-english',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'AETrainingDetail',
//     subMenuId: 30,
//     subMenus: false,
//     description: 'Advanced Aviation English description !',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 45,
//     name: 'Fly with the Flight Training Center',
//     url: 'fly-with-the-flight-training-center',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'ACGuidanceDetail',
//     subMenuId: 31,
//     subMenus: false,
//     description: 'Fly with the Flight Training Center description !',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 46,
//     name: 'Visit the Training Model of the Flight Training Center',
//     url: 'visit-the-training-model-of-the-flight-training-center',
//     img: 'article.jpg',
//     summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Enim dolorum nihil dolores temporibus repudiandae, quibusdam quasi quidem fugit, corporis quae nemo repellendus velit architecto laboriosam modi possimus nulla ipsum? Dolor?',
//     routeName: 'ACGuidanceDetail',
//     subMenuId: 31,
//     subMenus: false,
//     description: 'Visit the Training Model of the Flight Training Center description !',
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   }
// ]

// // TrainingServiceDetails
// trainingServiceDetails: [
//   {
//     id: 1,
//     name: 'Huấn luyện chuyển loại ATR72',
//     url: 'ATR72-type-rating-training-pl',
//     description: 'ATR72 Type Rating Training description',
//     routeName: 'PilotTrainingDetail',
//     serviceId: 1,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 2,
//     name: 'Huấn luyện chuyển loại A321',
//     url: 'A321-type-rating-training-pl',
//     description: 'A321 Type Rating Training description',
//     routeName: 'PilotTrainingDetail',
//     serviceId: 1,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 3,
//     name: 'Huấn luyện chuyển loại A330',
//     url: 'A330-type-rating-training-pl',
//     description: 'A330 Type Rating Training description',
//     routeName: 'PilotTrainingDetail',
//     serviceId: 1,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 4,
//     name: 'Huấn luyện chuyển loại A350',
//     url: 'A350-type-rating-training-pl',
//     description: 'A350 Type Rating Training description',
//     routeName: 'PilotTrainingDetail',
//     serviceId: 1,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 5,
//     name: 'Huấn luyện chuyển loại B777',
//     url: 'B777-type-rating-training-pl',
//     description: 'B777 Type Rating Training description',
//     routeName: 'PilotTrainingDetail',
//     serviceId: 1,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 6,
//     name: 'Huấn luyện chuyển loại B787',
//     url: 'B787-type-rating-training-pl',
//     description: 'B787 Type Rating Training description',
//     routeName: 'PilotTrainingDetail',
//     serviceId: 1,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 7,
//     name: 'Huấn luyện chuyển loại ATR72',
//     url: 'ATR72-type-rating-training-fa',
//     description: 'ATR72 Type Rating Training description B',
//     routeName: 'FATrainingDetail',
//     serviceId: 8,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 8,
//     name: 'Huấn luyện chuyển loại A321',
//     url: 'A321-type-rating-training-fa',
//     description: 'A321 Type Rating Training description B',
//     routeName: 'FATrainingDetail',
//     serviceId: 8,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 9,
//     name: 'Huấn luyện chuyển loại A330',
//     url: 'A330-type-rating-training-fa',
//     description: 'A330 Type Rating Training description B',
//     routeName: 'FATrainingDetail',
//     serviceId: 8,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 10,
//     name: 'Huấn luyện chuyển loại A350',
//     url: 'A350-type-rating-training-fa',
//     description: 'A350 Type Rating Training description B',
//     routeName: 'FATrainingDetail',
//     serviceId: 8,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 11,
//     name: 'Huấn luyện chuyển loại B777',
//     url: 'B777-type-rating-training-fa',
//     description: 'B777 Type Rating Training description B',
//     routeName: 'FATrainingDetail',
//     serviceId: 8,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 12,
//     name: 'Huấn luyện chuyển loại B787',
//     url: 'B787-type-rating-training-fa',
//     description: 'B787 Type Rating Training description B',
//     routeName: 'FATrainingDetail',
//     serviceId: 8,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 13,
//     name: 'ATR72 Type Rating Training',
//     url: 'ATR72-type-rating-training-pl',
//     description: 'ATR72 Type Rating Training description',
//     routeName: 'PilotTrainingDetail',
//     serviceId: 24,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 14,
//     name: 'A321 Type Rating Training',
//     url: 'A321-type-rating-training-pl',
//     description: 'A321 Type Rating Training description',
//     routeName: 'PilotTrainingDetail',
//     serviceId: 24,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 15,
//     name: 'A330 Type Rating Training',
//     url: 'A330-type-rating-training-pl',
//     description: 'A330 Type Rating Training description',
//     routeName: 'PilotTrainingDetail',
//     serviceId: 24,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 16,
//     name: 'A350 Type Rating Training',
//     url: 'A350-type-rating-training-pl',
//     description: 'A350 Type Rating Training description',
//     routeName: 'PilotTrainingDetail',
//     serviceId: 24,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 17,
//     name: 'B777 Type Rating Training',
//     url: 'B777-type-rating-training-pl',
//     description: 'B777 Type Rating Training description',
//     routeName: 'PilotTrainingDetail',
//     serviceId: 24,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 18,
//     name: 'B787 Type Rating Training',
//     url: 'B787-type-rating-training-pl',
//     description: 'B787 Type Rating Training description',
//     routeName: 'PilotTrainingDetail',
//     serviceId: 24,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 19,
//     name: 'ATR72 Type Rating Training',
//     url: 'ATR72-type-rating-training-fa',
//     description: 'ATR72 Type Rating Training description B',
//     routeName: 'FATrainingDetail',
//     serviceId: 31,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 20,
//     name: 'A321 Type Rating Training',
//     url: 'A321-type-rating-training-fa',
//     description: 'A321 Type Rating Training description B',
//     routeName: 'FATrainingDetail',
//     serviceId: 31,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 21,
//     name: 'A330 Type Rating Training',
//     url: 'A330-type-rating-training-fa',
//     description: 'A330 Type Rating Training description B',
//     routeName: 'FATrainingDetail',
//     serviceId: 31,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 22,
//     name: 'A350 Type Rating Training',
//     url: 'A350-type-rating-training-fa',
//     description: 'A350 Type Rating Training description B',
//     routeName: 'FATrainingDetail',
//     serviceId: 31,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 23,
//     name: 'B777 Type Rating Training',
//     url: 'B777-type-rating-training-fa',
//     description: 'B777 Type Rating Training description B',
//     routeName: 'FATrainingDetail',
//     serviceId: 31,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 24,
//     name: 'B787 Type Rating Training',
//     url: 'B787-type-rating-training-fa',
//     description: 'B787 Type Rating Training description B',
//     routeName: 'FATrainingDetail',
//     serviceId: 31,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   }
// ]

// // News x
// news: [
//   {
//     id: 1,
//     img: 'article.jpg',
//     title: 'Tuyển dụng giáo viên kiêm nhiệm các bộ môn an toàn khai thác đợt 3',
//     hidden: false,
//     summary: 'Tuyển dụng giáo viên kiêm nhiệm các bộ môn an toàn khai thác đợt 3',
//     description: 'Tuyển dụng giáo viên kiêm nhiệm các bộ môn an toàn khai thác đợt 3 ........',
//     url: 'Tuyen-dung-giao-vien-kiem-nhiem-cac-bo-mon-an-toan-khai-thac-dot-3',
//     menuId: 2,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 2,
//     img: 'article(1).jpg',
//     title: 'GIẤY PHÉP DẠY NGHỀ',
//     hidden: false,
//     summary: 'Ngày 1/12/2017 Sờ Lao động Thương binh và Xã hội đã cấp Giấy Chứn nhận đăng ký hoạt động giụo dạc dạy nghề cho Chi nhánh Tổng Công ty hang không Việt Nam - CTCP -Trung tâm Huấn luyện bay về đào tạo nghề Tiếp viên cơ bản; Phi công chuyển loại; Nhân viên điều hành bay và Điều phái bay cơ bản.',
//     description: 'Ngày 1/12/2017 Sờ Lao động Thương binh và Xã hội đã cấp Giấy Chứn nhận đăng ký hoạt động giụo dạc dạy nghề cho Chi nhánh Tổng Công ty hang không Việt Nam - CTCP -Trung tâm Huấn luyện bay về đào tạo nghề Tiếp viên cơ bản; Phi công chuyển loại; Nhân viên điều hành bay và Điều phái bay cơ bản.,  ........',
//     url: 'GIAY-PHEP-DAY-NGHE',
//     menuId: 2,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 3,
//     img: 'article(2).jpg',
//     title: 'LỄ KHAI TRƯƠNG SIM A320-200 SERIES 7000XR',
//     hidden: false,
//     summary: 'Với việc chính thức đưa vào khai thác SIM A320/321, VNA sẽ tiết kiệm được đáng kể chi phí thuê thiết bị huấn luyện tại nước ngoài cũng như chủ động hơn trong công tác đào tạo phi công, đáp ứng nhu...',
//     description: 'Với việc chính thức đưa vào khai thác SIM A320/321, VNA sẽ tiết kiệm được đáng kể chi phí thuê thiết bị huấn luyện tại nước ngoài cũng như chủ động hơn trong công tác đào tạo phi công, đáp ứng nhu.........',
//     url: 'LE-KHAI-TRUONG-SIM-A320-200-SERIES-7000XR',
//     menuId: 2,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 4,
//     img: 'article(3).jpg',
//     title: 'THƯ NGỎ',
//     hidden: false,
//     summary: 'Thành tựu TTHL đạt được ngày hôm nay là do sự nỗ lực, đóng góp của tập thể CBCNV, giáo viên và học viên. Để xây dựng môi trường huấn luyện chuyên nghiệp và giúp nhận diện thương hiệu TCTHK - hãng hàng không 4, TTHL đã thiết kế ra mẫu áo đồng phục dành cho học viên có logo biểu tượng của TCTHK và TTHL.',
//     description: 'Thành tựu TTHL đạt được ngày hôm nay là do sự nỗ lực, đóng góp của tập thể CBCNV, giáo viên và học viên. Để xây dựng môi trường huấn luyện chuyên nghiệp và giúp nhận diện thương hiệu TCTHK - hãng hàng không 4, TTHL đã thiết kế ra mẫu áo đồng phục dành cho học viên có logo biểu tượng của TCTHK và TTHL,.....',
//     url: 'THU-NGO',
//     menuId: 2,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 5,
//     img: 'article(4).jpg',
//     title: 'Thư feedback của học viên về lớp hướng nghiệp',
//     hidden: false,
//     summary: '"Một vài feedback của e về khóa hướng nghiệp nghề tiếp viên hàng không và phi công của trung tâm FTC VNA đã tổ chức ạ" - Đậu Phi Hùng',
//     description: '"Một vài feedback của e về khóa hướng nghiệp nghề tiếp viên hàng không và phi công của trung tâm FTC VNA đã tổ chức ạ" - Đậu Phi Hùng,.....',
//     url: 'Thu-feedback-cua-hoc-vien-ve-lop-huong-nghiep',
//     menuId: 2,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 6,
//     img: 'article.jpg',
//     title: 'Recruiting Teachers for Safety Operations Subjects (Round 3)',
//     hidden: false,
//     summary: 'Recruiting teachers for safety operations subjects (Round 3)',
//     description: 'Recruiting teachers for safety operations subjects (Round 3) ........',
//     url: 'Tuyen-dung-giao-vien-kiem-nhiem-cac-bo-mon-an-toan-khai-thac-dot-3',
//     menuId: 2,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 7,
//     img: 'article(1).jpg',
//     title: 'VOCATIONAL TEACHING LICENSE',
//     hidden: false,
//     summary: 'On 1/12/2017, the Department of Labor, Invalids, and Social Affairs issued a vocational teaching license to the Vietnam Airlines Corporation - Training Center for basic flight attendant training, type rating pilot training, flight operations personnel training, and basic dispatch training.',
//     description: 'On 1/12/2017, the Department of Labor, Invalids, and Social Affairs issued a vocational teaching license to the Vietnam Airlines Corporation - Training Center for basic flight attendant training, type rating pilot training, flight operations personnel training, and basic dispatch training. ........',
//     url: 'GIAY-PHEP-DAY-NGHE',
//     menuId: 2,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 8,
//     img: 'article(2).jpg',
//     title: 'INAUGURATION CEREMONY OF SIM A320-200 SERIES 7000XR',
//     hidden: false,
//     summary: 'With the official launch of the SIM A320/321, VNA will significantly save on overseas training equipment rental costs and become more proactive in pilot training, meeting the demand...',
//     description: 'With the official launch of the SIM A320/321, VNA will significantly save on overseas training equipment rental costs and become more proactive in pilot training, meeting the demand.........',
//     url: 'LE-KHAI-TRUONG-SIM-A320-200-SERIES-7000XR',
//     menuId: 2,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 9,
//     img: 'article(3).jpg',
//     title: 'OPEN LETTER',
//     hidden: false,
//     summary: 'The achievements of the Training Center today are due to the efforts and contributions of all staff, teachers, and students. To build a professional training environment and promote the brand identity of VNA - a 4-star airline, the Training Center has designed a uniform for students with the logo of VNA and the Training Center.',
//     description: 'The achievements of the Training Center today are due to the efforts and contributions of all staff, teachers, and students. To build a professional training environment and promote the brand identity of VNA - a 4-star airline, the Training Center has designed a uniform for students with the logo of VNA and the Training Center,.....',
//     url: 'THU-NGO',
//     menuId: 2,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 10,
//     img: 'article(4).jpg',
//     title: 'Student Feedback on Career Orientation Class',
//     hidden: false,
//     summary: '"Some feedback from me about the career orientation class for flight attendants and pilots organized by FTC VNA" - Đậu Phi Hùng',
//     description: '"Some feedback from me about the career orientation class for flight attendants and pilots organized by FTC VNA" - Đậu Phi Hùng,.....',
//     url: 'Thu-feedback-cua-hoc-vien-ve-lop-huong-nghiep',
//     menuId: 2,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   }
// ]

// // Admissions x
// admissions: [
//   {
//     id: 1,
//     img: 'article.jpg',
//     title: 'Tuyển sinh đợt 1 - 2024',
//     summary: 'Tuyển sinh tổng quát 1.',
//     description: 'Tuyển sinh chi tiết 1',
//     hidden: false,
//     url: 'tuyen-sinh-1',
//     subMenuId: 15,
//     lang: 'vn',
//     createdAt: '29/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 2,
//     img: 'article.jpg',
//     title: 'Tuyển sinh đợt 2 - 2024',
//     summary: 'Tuyển sinh tổng quát 2.',
//     description: 'Tuyển sinh chi tiết 2',
//     hidden: false,
//     url: 'tuyen-sinh-2',
//     subMenuId: 15,
//     lang: 'vn',
//     createdAt: '29/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 3,
//     img: 'article.jpg',
//     title: 'Admissions Round 1 - 2024',
//     summary: 'General Admissions 1.',
//     description: 'Detailed Admissions 1',
//     hidden: false,
//     url: 'tuyen-sinh-1',
//     subMenuId: 34,
//     lang: 'en',
//     createdAt: '29/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 4,
//     img: 'article.jpg',
//     title: 'Admissions Round 2 - 2024',
//     summary: 'General Admissions 2.',
//     description: 'Detailed Admissions 2',
//     hidden: false,
//     url: 'tuyen-sinh-2',
//     subMenuId: 34,
//     lang: 'en',
//     createdAt: '29/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   }
// ]

// // TrainingSchedules x
// trainingSchedules: [
//   { id: 1, name: 'Kế hoạch huấn luyện tháng 12', hidden: false, subMenuId: 17, lang: 'vn', createdAt: '30/05/2024', author: 'admin', updatedAt: '31/05/2024' },
//   { id: 2, name: 'Kế hoạch huấn luyện tháng 2/2018', hidden: false, subMenuId: 17, lang: 'vn', createdAt: '30/05/2024', author: 'admin', updatedAt: '31/05/2024' },
//   { id: 3, name: 'Kế hoạch huấn luyện tháng 3/2018', hidden: false, subMenuId: 17, lang: 'vn', createdAt: '30/05/2024', author: 'admin', updatedAt: '31/05/2024' },
//   { id: 4, name: 'Kế hoạch huấn luyện tháng 4/2018', hidden: false, subMenuId: 17, lang: 'vn', createdAt: '30/05/2024', author: 'admin', updatedAt: '31/05/2024' },
//   { id: 5, name: 'Kế hoạch huấn luyện tháng 5/2018', hidden: false, subMenuId: 17, lang: 'vn', createdAt: '30/05/2024', author: 'admin', updatedAt: '31/05/2024' },
//   { id: 6, name: 'Training Plan for December', hidden: false, subMenuId: 36, lang: 'en', createdAt: '30/05/2024', author: 'admin', updatedAt: '31/05/2024' },
//   { id: 7, name: 'Training Plan for February 2018', hidden: false, subMenuId: 36, lang: 'en', createdAt: '30/05/2024', author: 'admin', updatedAt: '31/05/2024' },
//   { id: 8, name: 'Training Plan for March 2018', hidden: false, subMenuId: 36, lang: 'en', createdAt: '30/05/2024', author: 'admin', updatedAt: '31/05/2024' },
//   { id: 9, name: 'Training Plan for April 2018', hidden: false, subMenuId: 36, lang: 'en', createdAt: '30/05/2024', author: 'admin', updatedAt: '31/05/2024' },
//   { id: 10, name: 'Training Plan for May 2018', hidden: false, subMenuId: 36, lang: 'en', createdAt: '30/05/2024', author: 'admin', updatedAt: '31/05/2024' }
// ]

// // TrainingScheduleDetails x
// trainingScheduleDetails: [
//   {
//     id: 1,
//     name: 'KHHL thang 12 - HV Phi cong',
//     url: 'KHHL-thang-12-HV-Phi-cong',
//     description: 'KHHL thang 12 - HV Phi cong description',
//     hidden: false,
//     trainingScheduleId: 1,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 2,
//     name: 'KHHL thang 12 - HV Tiep vien',
//     url: 'KHHL-thang-12-HV-Tiep-vien',
//     description: 'KHHL thang 12 - HV Tiep vien description',
//     hidden: false,
//     trainingScheduleId: 1,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 3,
//     name: 'KHHL thang 12 - Dich vu ben ngoai',
//     url: 'KHHL-thang-12-Dich-vu-ben-ngoai',
//     description: 'KHHL thang 12 - Dich vu ben ngoai description',
//     hidden: false,
//     trainingScheduleId: 1,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 4,
//     name: 'KHHL thang 12 - CBNV',
//     url: 'KHHL-thang-12-CBNV',
//     description: 'KHHL thang 12 - CBNV description',
//     hidden: false,
//     trainingScheduleId: 1,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 5,
//     name: 'KHHL thang 2 - HV Phi cong',
//     url: 'KHHL-thang-2-HV-Phi-cong',
//     description: 'KHHL thang 2 - HV Phi cong description',
//     hidden: false,
//     trainingScheduleId: 2,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 6,
//     name: 'KHHL thang 2 - HV Tiep vien',
//     url: 'KHHL-thang-2-HV-Tiep-vien',
//     description: 'KHHL thang 2 - HV Tiep vien description',
//     hidden: false,
//     trainingScheduleId: 2,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 7,
//     name: 'KHHL thang 2 - CBNV',
//     url: 'KHHL-thang-2-CBNV',
//     description: 'KHHL thang 2 - CBNV description',
//     hidden: false,
//     trainingScheduleId: 2,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 8,
//     name: 'KHHL thang 2 - Dich vu ben ngoai',
//     url: 'KHHL-thang-2-Dich-vu-ben-ngoai',
//     description: 'KHHL thang 2 - Dich vu ben ngoai description',
//     hidden: false,
//     trainingScheduleId: 2,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 9,
//     name: 'KHHL thang 3 - HV Phi cong',
//     url: 'KHHL-thang-3-HV-Phi-cong',
//     description: 'KHHL thang 3 - HV Phi cong description',
//     hidden: false,
//     trainingScheduleId: 3,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 10,
//     name: 'KHHL thang 3 - HV Tiep vien',
//     url: 'KHHL-thang-3-HV-Tiep-vien',
//     description: 'KHHL thang 3 - HV Tiep vien description',
//     hidden: false,
//     trainingScheduleId: 3,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 11,
//     name: 'KHHL thang 3 - CBNV',
//     url: 'KHHL-thang-3-CBNV',
//     description: 'KHHL thang 3 - CBNV description',
//     hidden: false,
//     trainingScheduleId: 3,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 12,
//     name: 'KHHL thang 4 - HV Phi cong',
//     url: 'KHHL-thang-4-HV-Phi-cong',
//     description: 'KHHL thang 4 - HV Phi cong description',
//     hidden: false,
//     trainingScheduleId: 4,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 13,
//     name: 'KHHL thang 4 - HV Tiep vien',
//     url: 'KHHL-thang-4-HV-Tiep-vien',
//     description: 'KHHL thang 4 - HV Tiep vien description',
//     hidden: false,
//     trainingScheduleId: 4,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 14,
//     name: 'KHHL thang 4 - CBNV',
//     url: 'KHHL-thang-4-CBNV',
//     description: 'KHHL thang 4 - CBNV description',
//     hidden: false,
//     trainingScheduleId: 4,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 15,
//     name: 'KHHL thang 4 - HV khac',
//     url: 'KHHL-thang-4-HV-khac',
//     description: 'KHHL thang 4 - HV khac description',
//     hidden: false,
//     trainingScheduleId: 4,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 16,
//     name: 'KHHL thang 5 - HV Phi cong',
//     url: 'KHHL-thang-5-HV-Phi-cong',
//     description: 'KHHL thang 5 - HV Phi cong description',
//     hidden: false,
//     trainingScheduleId: 5,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 17,
//     name: 'KHHL thang 5 - HV Tiep vien',
//     url: 'KHHL-thang-5-HV-Tiep-vien',
//     description: 'KHHL thang 5 - HV Tiep vien description',
//     hidden: false,
//     trainingScheduleId: 5,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 18,
//     name: 'KHHL thang 5 - CBNV',
//     url: 'KHHL-thang-5-CBNV',
//     description: 'KHHL thang 5 - CBNV description',
//     hidden: false,
//     trainingScheduleId: 5,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 19,
//     name: 'KHHL thang 5 - HV khac',
//     url: 'KHHL-thang-5-HV-khac',
//     description: 'KHHL thang 5 - HV khac description',
//     hidden: false,
//     trainingScheduleId: 5,
//     lang: 'vn',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 20,
//     name: 'Training program December - Pilot',
//     url: 'KHHL-thang-12-HV-Phi-cong',
//     description: 'Training program December - Pilot Description',
//     hidden: false,
//     trainingScheduleId: 6,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 21,
//     name: 'Training program December - Flight Attendant',
//     url: 'KHHL-thang-12-HV-Tiep-vien',
//     description: 'Training program December - Flight Attendant Description',
//     hidden: false,
//     trainingScheduleId: 6,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 22,
//     name: 'Training program December - External Services',
//     url: 'KHHL-thang-12-Dich-vu-ben-ngoai',
//     description: 'Training program December - External Services Description',
//     hidden: false,
//     trainingScheduleId: 6,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 23,
//     name: 'Training program December - Staff',
//     url: 'KHHL-thang-12-CBNV',
//     description: 'Training program December - Staff Description',
//     hidden: false,
//     trainingScheduleId: 6,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 24,
//     name: 'Training program February - Pilot Description',
//     url: 'KHHL-thang-2-HV-Phi-cong',
//     description: 'Training program February - Pilot',
//     hidden: false,
//     trainingScheduleId: 7,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 25,
//     name: 'Training program February - Flight Attendant',
//     url: 'KHHL-thang-2-HV-Tiep-vien',
//     description: 'Training program February - Flight Attendant Description',
//     hidden: false,
//     trainingScheduleId: 7,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 26,
//     name: 'Training program February - Staff',
//     url: 'KHHL-thang-2-CBNV',
//     description: 'Training program February - Staff Description',
//     hidden: false,
//     trainingScheduleId: 7,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 27,
//     name: 'Training program February - External Services',
//     url: 'KHHL-thang-2-Dich-vu-ben-ngoai',
//     description: 'Training program February - External Services Description',
//     hidden: false,
//     trainingScheduleId: 7,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 28,
//     name: 'Training program March - Pilot',
//     url: 'KHHL-thang-3-HV-Phi-cong',
//     description: 'Training program March - Pilot Desctiption',
//     hidden: false,
//     trainingScheduleId: 8,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 29,
//     name: 'Training program March - Flight Attendant',
//     url: 'KHHL-thang-3-HV-Tiep-vien',
//     description: 'Training program March - Flight Attendant Description',
//     hidden: false,
//     trainingScheduleId: 8,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 30,
//     name: 'Training program March - Staff',
//     url: 'KHHL-thang-3-CBNV',
//     description: 'Training program March - Staff Description',
//     hidden: false,
//     trainingScheduleId: 8,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 31,
//     name: 'Training program April - Pilot',
//     url: 'KHHL-thang-4-HV-Phi-cong',
//     description: 'Training program April - Pilot Description',
//     hidden: false,
//     trainingScheduleId: 9,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 32,
//     name: 'Training program April - Flight Attendant',
//     url: 'KHHL-thang-4-HV-Tiep-vien',
//     description: 'Training program April - Flight Attendant Description',
//     hidden: false,
//     trainingScheduleId: 9,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 33,
//     name: 'Training program April - Staff',
//     url: 'KHHL-thang-4-CBNV',
//     description: 'Training program April - Staff Description',
//     hidden: false,
//     trainingScheduleId: 9,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 34,
//     name: 'Training program April - Others',
//     url: 'KHHL-thang-4-HV-khac',
//     description: 'Training program April - Others Description',
//     hidden: false,
//     trainingScheduleId: 9,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 35,
//     name: 'Training program May - Pilot',
//     url: 'KHHL-thang-5-HV-Phi-cong',
//     description: 'Training program May - Pilot Description',
//     hidden: false,
//     trainingScheduleId: 10,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 36,
//     name: 'Training program May - Flight Attendant',
//     url: 'KHHL-thang-5-HV-Tiep-vien',
//     description: 'Training program May - Flight Attendant Description',
//     hidden: false,
//     trainingScheduleId: 10,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 37,
//     name: 'Training program May - Staff',
//     url: 'KHHL-thang-5-CBNV',
//     description: 'Training program May - Staff Description',
//     hidden: false,
//     trainingScheduleId: 10,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   },
//   {
//     id: 38,
//     name: 'Training program May - Others',
//     url: 'KHHL-thang-5-HV-khac',
//     description: 'Training program May - Others Description',
//     hidden: false,
//     trainingScheduleId: 10,
//     lang: 'en',
//     createdAt: '30/05/2024',
//     author: 'admin',
//     updatedAt: '31/05/2024'
//   }
// ]
